- hosts: master
  become: yes
  roles:
    - role: geerlingguy.certbot
  vars:
    certbot_auto_renew: false
    certbot_admin_email: "{{ email }}"
    certbot_create_if_missing: true
    certbot_certs:
      - domains:
        - "{{ git_domain }}"

# Nginx
- hosts: master
  become: yes
  roles:
    - role: geerlingguy.nginx
  handlers:
    - name: restart nginx
      become: yes
      service:
        name: nginx
        enabled: yes
        state: restarted
  tasks:
    - name: Create /etc/nginx/sites-enabled/git.conf
      template:
        src: git.conf.j2
        dest: /etc/nginx/sites-enabled/git.conf
      notify:
        - reload nginx
        - restart nginx

- hosts: master
  become: yes
  roles:
    - role: weareinteractive.ufw
  vars:
    ufw_reset: no
    ufw_logging: "off"
    ufw_rules:
      - { port: 2222, rule: allow, comment: 'Allow git ssh' }

