- platform: generic
  name: Vacuum Map
  still_image_url: http://localhost:10005/map.png
  framerate: 1

- platform: generic
  name: Vacuum Grid Map
  still_image_url: http://localhost:10005/map.grid.png
  framerate: 1

