- platform: webostv
  name: tv_notifications
  host: 192.168.1.141

- platform: slack
  name: slack
  api_key: !env_var HOME_ASSISTANT_SLACK_API_KEY
  default_channel: '#dom'
  icon: ':suspect:'

- platform: alexa_media
  name: alexa_media

- name: telegram_arek
  platform: telegram
  chat_id: 66368059

# Push messages using gotify server https://gotify.net/docs/pushmsg
- name: gotify
  method: POST
  platform: rest
  resource: !env_var HOME_ASSISTANT_GOTIFY_ENDPOINT

- name: lunching
  method: POST
  platform: rest
  resource: !env_var HOME_ASSISTANT_GOTIFY_LUNCHING_ENDPOINT

- name: all
  platform: group
  services:
    - service: slack
    - service: gotify
    - service: tv_notifications