- platform: wake_on_lan
  name: tv
  mac_address: "04:4E:AF:7A:CA:3A"

- platform: flux
  lights:
    - light.arek_szafka
    - light.ola_szafka
  brightness: 83
  mode: mired
  disable_brightness_adjust: true
  start_colortemp: 3500
  sunset_colortemp: 2800
  stop_colortemp: 2200

- platform: wake_on_lan
  name: Mac Mini
  mac_address: "D4:DC:CD:F3:FD:B6"

- platform: template
  switches:
    giggid:
      value_template: "{{ is_state('input_boolean.giggid', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.giggid
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.giggid
    pizza:
      value_template: "{{ is_state('input_boolean.pizza', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.pizza
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.pizza