# All media services, that don't need to be always online
version: '3.5'
services:
  airsonic:
    image: airsonic/airsonic
    network_mode: host
    ports:
      - 4040:4040
    volumes:
      - .docker/data/airsonic:/airsonic/data
      - /mnt/Music/airsonic/music:/airsonic/music
      - /mnt/Music/airsonic/playlists:/airsonic/playlists
      - /mnt/Music/airsonic/podcasts:/airsonic/podcasts
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  bazzar:
    image: linuxserver/bazarr:latest
    network_mode: host
    environment: 
      PUID: 0
      PGID: 0
      TZ: "Europe/Warsaw"
    ports:
      - 6767:6767
    volumes:
      - .docker/data/bazzar:/config
      - /mnt/MoviesAndTV:/tv
      - /mnt/Movies:/movies
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  sonarr:
    image: linuxserver/sonarr
    ports:
      - 8989:8989
    environment: 
      PUID: 0
      PGID: 0
      TZ: "Europe/Warsaw"
    volumes:
      - .docker/data/sonarr:/config
      - /mnt/MoviesAndTV:/tv
      - /home/downloads:/downloads
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  transmission:
    image: linuxserver/transmission:latest
    restart: unless-stopped
    ports:
      - 8112:9091
      - 51413:51413/udp
    environment: 
      PUID: 0
      PGID: 0
      TZ: "Europe/Warsaw"
    volumes:
      - .docker/data/transmission:/config
      - /mnt:/data
      - /mnt/MoviesAndTV:/tv
      - /smart-house/tmp:/downloads
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  plex:
    network_mode: host
    image: plexinc/pms-docker
    env_file:
      - .env.plex
    volumes: 
      - .docker/data/plex/config:/config
      - .docker/data/plex/transcode:/transcode
      - /mnt:/data
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
  ytdl:
    restart: unless-stopped
    image: macbury/yt-music-download-helper:latest
    ports:
      - 9292:9292
    volumes:
      - /tmp:/download
      - /mnt/Music:/output
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
