# All media services, that don't need to be always online
version: '3.5'

volumes:  
  music:   
    driver: cifs 
    driver_opts:
      share: mr-pickle.here/Music
  movies:   
    driver: cifs 
    driver_opts:
      share: mr-pickle.here/Movies
  tv:   
    driver: cifs 
    driver_opts:
      share: mr-pickle.here/MoviesAndTV
  photos:   
    driver: cifs 
    driver_opts:
      share: mr-pickle.here/Multimedia
  downloads:   
    driver: cifs 
    driver_opts:
      share: mr-pickle.here/UsbDisk

services:
  emby:
    image: emby/embyserver:latest
    ports:
      - 8096:8096
    environment:
      - UID=1000
      - GID=100 
      - GIDLIST=100,44,1
      - TZ=Warsaw
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - .docker/data/emby/config:/config
      - movies:/mnt/Movies
      - tv:/mnt/MoviesAndTV
      - photos:/mnt/Multimedia
      - music:/mnt/Music
  lidarr:
    image: linuxserver/lidarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Warsaw
      - UMASK_SET=022 #optional
    volumes:
      - .docker/data/lidarr:/config
      - music:/music
      - downloads:/downloads
    ports:
      - "0.0.0.0:18686:8686"
    restart: unless-stopped
    depends_on:
      - torrents
      - emby
  sonarr:
    image: linuxserver/sonarr
    ports:
      - 8989:8989
    environment:
      PUID: 0
      PGID: 0
      TZ: "Europe/Warsaw"
    volumes:
      - .docker/data/sonarr:/config
      - tv:/tv
      - downloads:/downloads
    depends_on:
      - torrents
      - emby
  torrents:
    image: linuxserver/deluge:latest
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - TZ=Warsaw
      - DELUGE_LOGLEVEL=info #optional
    volumes:
      - .docker/data/deluge/config:/config
      - movies:/data/Movies
      - tv:/data/MoviesAndTV
      - music:/data/Music
      - downloads:/data/UsbDisk
    restart: unless-stopped
