# All media services, that don't need to be always online
version: '3.5'

services:
  emby:
    image: emby/embyserver:beta
    ports:
      - 8096:8096
    environment:
      - UID=1000
      - GID=100 
      - GIDLIST=100,44,1,0,1003
      - TZ=Warsaw
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - .docker/data/emby/config:/config
      - /mnt/Movies:/mnt/Movies
      - /mnt/Books:/mnt/Books
      - /mnt/MoviesAndTV:/mnt/MoviesAndTV
      - /mnt/Multimedia:/mnt/Multimedia
      - /mnt/Music:/mnt/Music