# All media services, that don't need to be always online
version: '3.5'
services:
  bazzar:
    image: linuxserver/bazarr:latest
    network_mode: host
    environment:
      PUID: 0
      PGID: 0
      TZ: "Europe/Warsaw"
    ports:
      - 6767:6767
    volumes:
      - .docker/data/bazzar:/config
      - /mnt/MoviesAndTV:/tv
      - /mnt/Movies:/movies
  sonarr:
    image: linuxserver/sonarr
    ports:
      - 8989:8989
    environment:
      PUID: 0
      PGID: 0
      TZ: "Europe/Warsaw"
    volumes:
      - .docker/data/sonarr:/config
      - /mnt/MoviesAndTV:/tv
      - /mnt/UsbDisk:/downloads
  plex:
    network_mode: host
    image: plexinc/pms-docker:latest
    env_file:
      - .env.plex
    volumes:
      - .docker/data/plex/config:/config
      - .docker/data/plex/transcode:/transcode
      - /mnt:/data
  torrents:
    image: linuxserver/deluge:latest
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Warsaw
      - DELUGE_LOGLEVEL=info #optional
    volumes:
      - .docker/data/deluge/config:/config
      - /mnt:/data
    restart: unless-stopped
