# All media services, that don't need to be always online
version: '3.5'
services:
  bazzar:
    image: linuxserver/bazarr:latest
    network_mode: host
    environment:
      PUID: 0
      PGID: 0
      TZ: "Europe/Warsaw"
    ports:
      - 6767:6767
    volumes:
      - .docker/data/bazzar:/config
      - /mnt/MoviesAndTV:/tv
      - /mnt/Movies:/movies
  sonarr:
    image: linuxserver/sonarr
    ports:
      - 8989:8989
    environment:
      PUID: 0
      PGID: 0
      TZ: "Europe/Warsaw"
    volumes:
      - .docker/data/sonarr:/config
      - /mnt/MoviesAndTV:/tv
      - /home/downloads:/downloads
  transmission:
    image: linuxserver/transmission:latest
    restart: unless-stopped
    ports:
      - 8112:9091
      - 51413:51413/udp
    environment:
      PUID: 0
      PGID: 0
      TZ: "Europe/Warsaw"
    volumes:
      - .docker/data/transmission:/config
      - /mnt:/data
      - /mnt/MoviesAndTV:/tv
      - /smart-house/tmp:/downloads
  plex:
    network_mode: host
    image: plexinc/pms-docker:1.18.3.2156-349e9837e
    env_file:
      - .env.plex
    volumes:
      - .docker/data/plex/config:/config
      - .docker/data/plex/transcode:/transcode
      - /mnt:/data
  monio:
    restart: unless-stopped
    image: macbury/mon.io:latest
    network_mode: host
    volumes:
      - .docker/data/monio/:/app/storage
    env_file:
      - .env.monio
