# Small laboratory
version: '3.5'

services:
  tor:
    restart: unless-stopped
    build: ./tor/
    ports:
      - 9050:9050
      - 9051:9051
    volumes:
      - .docker/data/tor:/data
  btc-explorer:
    restart: unless-stopped
    build: ./btc-explorer/
    ports:
      - 19080:19080
    env_file:
      - '.env.bitcoind'
