# Small labolatory
version: '3.5'

services:
  eth:
    image: ethereum/client-go:alltools-v1.9.12
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./.docker/data/eth/data:/data
      - ./.docker/data/eth/settings:/settings
      - ./ethereum/boot.sh:/boot.sh
    command: "./boot.sh"
    env_file:
      - '.env.ethereum'