# https://stadicus.github.io/RaspiBolt/

# configure firewall
# change docker data directory to /data
# set command for unlock hard drive

# systemd service for torrents
  # mount usb disk
  # mount other directories
  # start docker image like pihole
# systemd service for media
  # the same as torrents
# ipfs
  # install ipfs and deamon
  # like torrents
# bitcoin core
  # like torrents

# - hosts: anarchopi
#   become: yes
#   tasks:
#     - apt:
#         name: build-essential
#     - apt:
#         name: libffi-dev
#     - apt:
#         name: libssl-dev
#     - name: Install cryptsetup
#       apt:
#         name: cryptsetup
#     - name: smb
#       apt:
#         name: cifs-utils

# - hosts: anarchopi
#   become: yes
#   roles:
#     - role: weareinteractive.ufw
#   vars:
#     ufw_reset: yes
#     ufw_logging: "off"
#     ufw_rules:
#       - { port: 22, rule: allow, comment: "Allow ssh" }

# - name: Configure torrents
#   import_playbook: torrents/torrents.yaml

# - name: Configure bitcoin
#   import_playbook: bitcoind/bitcoin.yaml

# - name: Configure lnd
#   import_playbook: lnd/lnd.yaml