- hosts: master
  become: yes
  roles:
    - role: weareinteractive.ufw
  vars:
    ufw_reset: no
    ufw_logging: "off"
    ufw_rules:
      - { port: 8112, rule: allow, comment: 'Allow Sonarr access to deluge' }
# Nginx
- hosts: master
  become: yes
  roles:
    - role: geerlingguy.nginx
  handlers:
    - name: restart nginx
      become: yes
      service:
        name: nginx
        enabled: yes
        state: restarted
  tasks:
    - name: Create /etc/nginx/sites-enabled/torrents.conf
      template:
        src: torrents.conf.j2
        dest: /etc/nginx/sites-enabled/torrents.conf
      notify:
        - reload nginx
        - restart nginx