- hosts: master
  become: yes
  vars:
    certbot_auto_renew: false
    certbot_admin_email: "{{ email }}"
    certbot_create_if_missing: true
    certbot_certs:
      - domains:
        - "{{ electrum_domain }}"
  roles:
    - role: geerlingguy.nginx
    - role: geerlingguy.certbot
  handlers:
    - name: restart nginx
      become: yes
      service:
        name: nginx
        enabled: yes
        state: restarted
  tasks:
    - name: Create /etc/nginx/sites-enabled/electrum.conf
      template:
        src: electrum.conf.j2
        dest: /etc/nginx/sites-enabled/electrum.conf
      notify:
        - reload nginx
        - restart nginx

- hosts: anarchopi
  become: yes
  roles:
    - role: weareinteractive.ufw
  vars:
    ufw_reset: no
    ufw_logging: "off"
    ufw_rules:
      - { port: 50001, rule: allow, comment: "Expose electrs rpc" }
      - { port: 50002, rule: allow, comment: "Expose electrs" }
  tasks:
    - name: Install clang
      apt:
        name: clang
    - name: Install cmake
      apt:
        name: cmake 
    - name: Check if rust is installed
      command: 'rustc --version'
      register: rust_is_installed
      ignore_errors: True
    - name: Download rust
      when: rust_is_installed is failed
      get_url:
        url: https://static.rust-lang.org/dist/rust-1.42.0-armv7-unknown-linux-gnueabihf.tar.gz
        dest: /tmp/rust.tar.gz
    - name: Extract rust
      when: rust_is_installed is failed
      unarchive:
        remote_src: yes
        src: /tmp/rust.tar.gz
        dest: /tmp
    - name: Install rust
      when: rust_is_installed is failed
      command: bash /tmp/rust-1.42.0-armv7-unknown-linux-gnueabihf/install.sh
    - name: Check if electrs is installed
      command: 'electrs  --help'
      register: electrs_is_installed
      ignore_errors: True
    - name: Clone electrs repo
      when: electrs_is_installed is failed
      git:
        repo: https://github.com/romanz/electrs.git
        dest: /home/pi/electrs
        accept_hostkey: yes
        update: yes
    - name: Compile electrs
      when: electrs_is_installed is failed
      command: 
        cmd: 'cargo build --release'
        chdir: /home/pi/electrs
    - name: Install electrs
      when: electrs_is_installed is failed
      copy:
        remote_src: true
        src: /home/pi/electrs/target/release/electrs
        dest: /usr/local/bin/
    - name: Create directory
      file:
        group: bitcoin
        owner: bitcoin
        path: /data/electrs
        state: directory
    - name: Create symbolic link
      become: yes
      file:
        group: bitcoin
        owner: bitcoin
        src: /data/electrs
        dest: /home/bitcoin/.electrs
        state: link
    - name: Create backup directory
      file:
        group: bitcoin
        owner: bitcoin
        path: /data/backup/
        state: directory
    - name: Mount backup directory
      mount:
        state: mounted
        fstype: cifs
        opts: "domain=mr-pickle.here,username={{ qnap_username }},password={{ qnap_password }},file_mode=0664,dir_mode=0775,gid=bitcoin,uid=bitcoin"
        src: "//mr-pickle.here/SDDisk1"
        path: "/data/backup"
    - name: Upload backup script
      template:
        src: backup.j2
        dest: /usr/local/bin/raspibolt-backup
        mode: '0555'
    - name: Create electrs.service
      template:
        src: electrs.service
        dest: /lib/systemd/system/electrs.service
    - name: Restart service electrs.service
      systemd:
        state: started
        daemon_reload: yes
        name: electrs