- platform: uptime
- platform: glances
  host: localhost
  port: 4108
  version: 3
  resources:
    - 'disk_use_percent'
    - 'memory_use_percent'
    - 'swap_use_percent'
    - 'processor_load'
    - 'process_running'
    - 'process_total'
    - 'cpu_use_percent'
    - 'cpu_temp'
    - 'docker_active'
    - 'docker_cpu_use'
    - 'docker_memory_use'