
- hosts: 
    - master
    - dev
  become: yes
  handlers:
    - name: reload systemctl
      become: yes
      command: systemctl daemon-reload
    - name: restart systemd-resolved
      service:
        name: systemd-resolved
        state: restarted
  tasks:
    - apt:
        name: nfs-common
    - name: Ensure a locale exists
      locale_gen:
        name: en_GB.UTF-8
        state: present
    - name: Adding docker apt-key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: 'Adding repository'
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }}  stable
        state: present
    - name: Update repositories cache and install "docker-ce" package
      apt:
        name: docker-ce
        update_cache: yes
    - name: 'Docker compose'
      pip:
        name: docker-compose
    - name: Adding user {{ ansible_user }} to group docker
      user:
        name: '{{ ansible_user }}'
        group: docker
        append: yes
    - name: Download docker-volume-netshare
      get_url:
        url: https://github.com/ContainX/docker-volume-netshare/releases/download/v0.36/docker-volume-netshare_0.36_amd64.deb
        dest: "/tmp/docker-volume-netshare.deb"
    - name: Install docker-volume-netshare
      apt: 
        deb: /tmp/docker-volume-netshare.deb
      sudo: true
    - name: Create docker-netshare.service
      template:
        src: ./docker-netshare.service
        dest: /lib/systemd/system/docker-netshare.service
      notify:
        - reload systemctl