- hosts: anarchopi
  become: yes
  roles:
    - role: weareinteractive.ufw
  vars:
    bitcoin_version: 0.20.0
    ufw_reset: no
    ufw_logging: "off"
    ufw_rules:
      - { port: 8333, rule: allow, comment: "Expose p2p bitcoin port" }
      - { port: 8332, rule: allow, comment: "Expose p2p bitcoin port" }
      - { port: 50001, rule: allow, comment: "Expose rpc bitcoin port" }
      
  tasks:
    - name: Create bitcoins group
      group:
        name: bitcoin
    - name: Create bitcoin user
      user:
        name: bitcoin
        group: bitcoin
    - name: Create directory
      file:
        group: bitcoin
        owner: bitcoin
        path: /data/bitcoin
        state: directory
    - name: Create symbolic link
      become: yes
      file:
        group: bitcoin
        owner: bitcoin
        src: /data/bitcoin
        dest: /home/bitcoin/.bitcoin
        state: link
    - name: Check if bitcoin is installed
      command: 'bitcoind --version'
      register: bitcoin_is_installed
      ignore_errors: True
    - name: Download bitcoin core
      when: bitcoin_is_installed is failed
      get_url:
        url:  https://bitcoincore.org/bin/bitcoin-core-{{ bitcoin_version }}/bitcoin-{{ bitcoin_version }}-arm-linux-gnueabihf.tar.gz
        dest: /tmp/bitcoin.tar.gz
    - name: Extract bitcoin core
      when: bitcoin_is_installed is failed
      unarchive:
        remote_src: yes
        src: /tmp/bitcoin.tar.gz
        dest: /tmp
    - name: Install bitcoin core
      when: bitcoin_is_installed is failed
      command: install -m 0755 -o root -g root -t /usr/local/bin /tmp/bitcoin-{{ bitcoin_version }}/bin/*
    - name: Create bitcoind.service
      template:
        src: bitcoind.service
        dest: /lib/systemd/system/bitcoind.service
    - name: Restart service bitcoind.service
      systemd:
        state: started
        daemon_reload: yes
        name: bitcoind

- hosts: master
  become: yes
  roles:
    - role: geerlingguy.nginx
  handlers:
    - name: restart nginx
      become: yes
      service:
        name: nginx
        enabled: yes
        state: restarted
  tasks:
    - name: Create /etc/nginx/sites-enabled/btc-explorer.conf
      template:
        src: btc_explorer.conf.j2
        dest: /etc/nginx/sites-enabled/btc-explorer.conf
      notify:
        - reload nginx
        - restart nginx