- alias: Notify people if dish washing is complete
  trigger:
    - platform: state
      entity_id: binary_sensor.dishwasher
      to: 'off'
      from: 'on'
  action:
    - service: notify.alexa_media_living_room
      data:
        message: 'Hey yolo, dish washing is finished!'
        data:
          type: announce
          method: all
    - delay: '00:00:15'
    - service: notify.all
      data:
        message: '@here, naczynia są umyte'

- alias: Notify wife that clothes washing is complete
  trigger:
    - platform: state
      entity_id: binary_sensor.washer
      to: 'off'
      from: 'on'
  action:
    - service: notify.alexa_media_living_room
      data:
        message: 'Hey wife, loundry is finished!'
        data:
          type: announce
          method: all
    - delay: '00:00:15'
    - service: notify.all
      data:
        message: '@Ola, pranie się skończyło!'