- alias: Notify puny humans about feeding of the overlord
  trigger:
    - platform: state
      entity_id: calendar.pushi
      to: 'on'
      from: 'off'
  condition:
    - condition: state
      entity_id: group.family
      state: home
  action:
    - service: notify.alexa_media_living_room
      data:
        message: 'Attention puny humans. Himen needs pushi now!'
        data:
          type: announce
          method: all
    - service: notify.alexa_media_kitchen
      data:
        message: 'Attention puny humans. Himen needs pushi now!'
        data:
          type: announce
          method: all
    - delay: '00:00:15'
    - service: notify.all
      data:
        message: 'Puss needs a attention!'

- alias: Switch on corridor lights after cat shitter is opened
  trigger:
    - platform: state
      entity_id: binary_sensor.cat_shitter_door
      to: 'on'
      from: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'sun.sun'
        state: 'below_horizon'
  action:
    - service: light.turn_on
      data:
        entity_id: light.corridor