- alias: Motion trigger
  trigger:
    - platform: webhook
      webhook_id: kitchen_cat_feeder_motion
  action:
    - service: light.turn_on
      entity_id: light.puss_feeder_light
      data:
        effect: Manual
        brightness: 255
        rgb_color: [255, 255, 255]

    - delay: '00:01:00'
    - service: light.turn_off
      entity_id: light.puss_feeder_light
- alias: Notify puny humans about feeding of the overlord
  trigger:
    - platform: state
      entity_id: calendar.pushi
      to: 'on'
      from: 'off'
  condition:
    - condition: state
      entity_id: group.family
      state: home
  action:
    - service: notify.alexa_media_living_room
      data:
        message: 'Attention puny humans. Himen needs pushi now!'
        data:
          type: announce
          method: all
    - service: notify.alexa_media_kitchen
      data:
        message: 'Attention puny humans. Himen needs pushi now!'
        data:
          type: announce
          method: all
    - delay: '00:00:15'
    - service: notify.all
      data:
        message: 'Puss needs a attention!'

- alias: Switch on corridor lights after cat shitter is opened
  trigger:
    - platform: state
      entity_id: binary_sensor.cat_shitter_door
      to: 'on'
      from: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'sun.sun'
        state: 'below_horizon'
  action:
    - service: light.turn_on
      data:
        entity_id: light.corridor

- alias: Feed the cat
  trigger:
    - platform: state
      entity_id: 'binary_sensor.iss'
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: calendar.cat_feed_schedule
      from: 'off'
      to: 'on'
  action:
    - service: script.feed_the_cat

- alias: Quick Feed The Cat
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.wall_switch_quick_feed_the_cat
      click_type: single
  action:
    - service: script.quick_feed_the_cat
