- alias: Send notification about humidifier water is out
  trigger:
    - platform: numeric_state
      entity_id: sensor.living_room_humidifier_current
      below: 0.01
      for:
        minutes: 1
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'switch.living_room_humidifier'
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.living_room_humidifier_current
        below: 0.01
  action:
    - service: notify.all
      data:
        message: 'Living room humidifier needs refill!'