- alias: Notify me that my train card will expire
  trigger:
    - platform: time
      at: '18:00:00'
  condition:
    - condition: template
      value_template: '{{ states.sensor.arek_karta_miejsca.attributes.days <= 4 }}'
  action:
    - service: notify.all
      data:
        message: '@Arek, twoja karta miejska wygaśnie za {{ states.sensor.arek_karta_miejsca.attributes.days }} dni! Kup nowy bilet tutaj: https://ebilet.kkm.krakow.pl/ebilet/Logowanie'

- alias: Nag me at the morning about next train
  trigger:
    platform: numeric_state
    entity_id: sensor.to_work_transit
    below: 600
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'person.arek'
        state: 'home'
      - condition: time
        # At least one of the following is required.
        after: '7:30:00'
        before: '9:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    - service: notify.all
      data:
        message: >
          @Arek, następny tramwaj za 10 min({{ states.sensor.to_work_transit.attributes.departures[0].time['formatted'] }})!
          Kolejny będzie o {{ states.sensor.to_work_transit.attributes.departures[1].time['formatted'] }}

