- alias: Summon vacuum back to dock if sombody returns to home
  trigger:
    platform: state
    entity_id: group.family
    from: 'not_home'
    to: 'home'
  action:
    - service: vacuum.return_to_base
      data:
        entity_id: vacuum.main_vacuum
    - service: vacuum.set_fan_speed
      data_template:
        entity_id: vacuum.living_room_vacum
        fan_speed: Balanced

- alias: Start cleaning the house
  trigger:
    platform: state
    entity_id: group.family
    from: 'home'
    to: 'not_home'
    for:
      minutes: 5
  action:
    - service: vacuum.start
      data:
        entity_id: vacuum.main_vacuum
    - delay: '00:00:05'
    - service: vacuum.set_fan_speed
      data_template:
        entity_id: vacuum.main_vacuum
        fan_speed: Balanced

- alias: Send vacuum near trash bin and ask for replacing trash can
  trigger:
    platform: state
    entity_id: vacuum.main_vacuum
    to: 'docked'
  condition:
    - condition: template
      value_template: '{{ states.vacuum.main_vacuum.attributes.cleaning_count % 10 == 0 }}'
  action:
    - service: notify.slack
      data:
        title: 'Odkurzacz'
        message: "Wyrzuć śmieci z pojemnika odkurzacza"
        # add go to target...
  
- alias: Summon vacuum to trash bin if is docked
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.kitchen_summon_vacuum
      click_type: single
  condition:
    - condition: state
      entity_id: vacuum.main_vacuum
      state: docked
  action:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.main_vacuum
        command: app_goto_target
        params: [25849, 24429]
    - service: notify.alexa_media_kitchen
      data:
        message: 'Hey, vacuum take your ass near trash can!'
        data:
          type: announce
          method: all

- alias: Send back vacuum to its cave
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.kitchen_summon_vacuum
      click_type: single
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: vacuum.main_vacuum
        state: cleaning
      - condition: state
        entity_id: vacuum.main_vacuum
        state: idle
  action:
    - service: vacuum.return_to_base
      data:
        entity_id: vacuum.main_vacuum
    - service: notify.alexa_media_kitchen
      data:
        message: 'Ok, thats is all, go back to your cave!'
        data:
          type: announce
          method: all